# Generated by Django 3.0.5 on 2020-04-03 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_pi', models.CharField(blank=True, max_length=200, verbose_name='Tag PI')),
                ('TimeStamp', models.DateTimeField(default=datetime.date.today, verbose_name='TimeStamp')),
                ('Value', models.FloatField(default=0, verbose_name='Value')),
            ],
        ),
    ]
